:rootdir: .
:imagesdir: {rootdir}/images

ifdef::env-github,env-browser[:badges:]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

= EtherUp

Bootstrap project to start working with https://ethereumclassic.github.io/[ethereum classic] as quickly as possible.

== Requirements

* Install https://www.virtualbox.org/wiki/Downloads[VirtualBox]
* Install https://www.vagrantup.com/downloads.html[Vagrant]
* Install http://www.groovy-lang.org/download.html#sdkman[Groovy]

== How to run

Set up local https://ethcore.io/parity.html[parity node]:

----
vagrant up
----

Check parity client version (link:./examples/client_version.groovy[client_version]):

----
> examples/client_version.groovy
Client version: Parity//v1.5.2-beta-948a538-20170208/x86_64-linux-gnu/rustc1.15.0
----

Receive test account balance (link:./examples/account_balance.groovy[account_balance]):

----
> examples/account_balance.groovy
Test account balance: 1606938044258990275541962092341162602522202.9938 ether
----

Tear down local parity node:

----
vagrant halt
----

== Customization

https://ethcore.io/parity.html[Parity] is an Ethereum client actively developed as an open source project.

There are a default configuration (link:./parity/default.toml[parity/default.toml]) used by default by Vagrant.

However, you are free to use your own alternative variants, for example:

----
env CONFIG=with_dapps CHAIN=example1 vagrant up
----

or even:

----
env CONFIG=with_dapps CHAIN=example1 vagrant provision
----

In these examples are used simple name conventions.
'`with_dapps`' implies the existence of configuration file at 'parity/with_dapps.toml'.
For chain '`example1`' it corresponds to 'parity/chain/example1.json' respectively.

== Licence

Apache 2.0
